### ISSUE TITLE
Missing input data in Simulate counterfacutals.R script

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/CounterfactualCovid19-inputs#5]
Hi @KFArnold, i'm trying to run the Simulate counterfacutals.R code and I get an error in line [31](https://github.com/alan-turing-institute/CounterfactualCovid19-inputs/blob/e4cfc777fbdeaf194593fc2e620a75c7a07731ca/Code/Simulate%20counterfactuals.R#L31) , with the error:

```  object 'data_eur' not found```

I think that variable is not defined in the previous Format data.R script. I'm I missing something?

**Comment by KFArnold** [comment]
It's not defined in a previous script but in the one you're working in, since it's just the data_eur dataframe which is subset by the specified country (i.e. data_eur_country <- data_eur %>% filter(Country == country)). So I'm not sure why it's throwing up an error. I've just finished resolving Issue 2 (updating the scripts to read in already-formatted data). Do you want to try running the script from that branch (i.e. feature/2-output-formatted-data) and see if you still get the same issue?

**Comment by KFArnold** [comment]
Oh wait, hold on I misread the issue - I thought the variable data_eur_country wasn't found! data_eur is defined in the 'Format data.R' script, so I don't know why it's showing an error. 

In any case, I think it's best to try from the new branch and see if it's still an issue!

**Comment by crangelsmith** [comment]
Thanks @KFArnold , I confirm that this issue is fixed in PR #2 :)
